---
- hosts: cluster
  tasks:
  - name: "Set authorized key took from file"
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
