#!/usr/bin/python
'sudo apt-get install -y software-properties-common'
'sudo apt-add-repository ppa:ansible/ansible'
'sudo apt-get update'
'sudo apt-get install -y ansible'
'sudo apt-get install openssh-server'
'ssh-keygen -t rsa -q -f /home/vagrant/.ssh/id_rsa -P ""'
'sudo cp /home/vagrant/hosts/ansible_hosts /etc/ansible/hosts'
'sudo service ssh restart'
'sudo chmod 777 ~/.ansible -R'
'sudo chmod 766 ~/.ssh'
'sudo chmod 766 ~/.ssh/id_rsa'
'sudo /home/vagrant/hosts/scan.py'
'ansible-playbook /home/vagrant/hosts/playbook/pubkey.yaml -e "ansible_user=vagrant ansible_sudo_pass=vagrant ansible_ssh_pass=vagrant "'
