---
- hosts: worker3
  become: yes
  tasks:
  - name: "Get CMS list file"
    get_url: 
      url: "https://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list"
      dest: "/etc/apt/sources.list.d/cloudera-manager.list"

  - shell: apt-get update
    
  - name: " install Cloudera Manager Agent"
    apt:
      name: cloudera-manager-agent
      state: installed
      allow_unauthenticated: yes


