---
      - name: master
        box: "ubuntu/trusty64"
        ram: "10000"
        cpu: "2" 
        ip: "192.168.0.100"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: manager
        box: "ubuntu/trusty64"
        ram: "12000"
        cpu: "2" 
        ip: "192.168.0.101"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker1
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.102"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker2
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.103"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker3
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.104"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker4
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1"
        ip: "192.168.0.105"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker5
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1"
        ip: "192.168.0.106"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: worker6
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1"
        ip: "192.168.0.107"
        folder: '/home/vagrant/BenchmarksEdition'

      - name: elephent
        box: "ubuntu/trusty64"
        ram: "10000"
        cpu: "2"
        ip: "192.168.0.108"
        provision: "gw.sh"
        folder: '/home/vagrant/BenchmarksEdition'
