---
- hosts: cluster
  become: yes
  tasks:
   - name: " Add Repo JDK"
     apt_repository:
       repo: ppa:webupd8team/java
       update_cache: yes

   - name: "FIx Bug"
     shell : sudo dpkg --configure -a

   - name: "Auto aceept JDK"
     shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

   - name: "Install JDK"
     shell: apt-get install -y oracle-java8-installer ca-certificates

   - name: "Java_HOME Variables"
     shell: export JAVA_HOME=/usr/lib/jvm/java-7-oracle

   - name: "JRE_HOME Vraiable"
     shell: export JRE_HOME=/usr/lib/jvm/java-7-oracle/jre

   - name: "Get CMS list file"
     get_url: 
       url: "https://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list"
       dest: "/etc/apt/sources.list.d/cloudera-manager.list"

   - shell: apt-get update
    
   - name: " install Cloudera Manager Agent"
     apt:
       name: cloudera-manager-agent
       state: installed
       allow_unauthenticated: yes

