---
# tasks file for preinstall
- name: "Install python 2.7" 
  sudo: yes
  apt:
    name: python2.7
    state: present

- name: "Disable IPV6"
  become: yes
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
  become: yes

- name: "Congiure use of swapinness"
  become: yes
  sysctl:
    name: vm.swappiness
    value: 10
    state: present
  tags: swap

- name: "Set Full Privilage to cma user"
  become: yes
  copy:
    src: sudoers
    dest: /etc/sudoers
  tags: cma

- name: "Create Cloudera Manager Service User"
  become: yes
  user:
    name: cma
    password: $6$eM1eZChnXKftJP$hVLcu3lx6FmGr4H3w1dVBh.dOhC6OJz0gFvM0vYkYJK9HjUGDfuTxmgXubN.SiYm2S.1VMjmYy9PSymM4BawU.
    group: sudo
    shell: "/bin/bash"
  tags: cma

- name: "Get CMS list file"
  become: yes
  get_url: 
    url: "https://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list"
    dest: "/etc/apt/sources.list.d/cloudera-manager.list"
  tags:
  - agent 
  - jdk

- name: "Upadte Cache" 
  become: yes
  apt:
    update_cache: yes

- name: "Install JDK"
  become: yes
  apt:
    name: oracle-j2sdk1.7
    state: installed
    allow_unauthenticated: yes
  #with_items:
  #- oralce-j2sdk1.7
  #- oralce-j2sdk1.6
  tags: jdk

- name: " install Cloudera Manager Agent"
  become: yes
  apt:
    name: cloudera-manager-agent
    state: installed
    allow_unauthenticated: yes
  tags: agent


 
  
