---
# tasks file for lvm
- name: " Ask for vars to create LVM"
  vars:
  - name: pattion of disk
  parttion_disk: `/home/vagrant/hosts
  vars_prompt:
  - name: lv_name
    prompt: " Enter LV Name"
  - name: size
    prompt: "enter size of disk"

- name: "get disk parttion"
  script: /home/vagrant
- name: create lvm to hosts
  lvol:
    vg:
