#!/usr/bin/python
import os
os.system('sudo apt-add-repository ppa:ansible/ansible')
os.system('sudo apt-get update')
os.system('sudo apt-get install -y ansible')
os.system('sudo apt-get install openssh-server')
os.system('sudo cp /home/vagrant/fullstack/hosts /etc/hosts')
os.system('ssh-keygen -t rsa -q -f /home/vagrant/.ssh/id_rsa -P ""')
os.system('sudo cp /home/vagrant/fullstack/ansible_hosts /etc/ansible/hosts')
os.system('sudo service ssh restart')
os.system('sudo chmod 777 ~/.ansible -R')
os.system('sudo chmod 766 ~/.ssh')
os.system('sudo chmod 766 ~/.ssh/id_rsa')
os.system('sudo service ssh restart')
os.system('sudo /home/vagrant/fullstack/scan.py')
