---
      - name: master1
        box: "ubuntu/trusty64"
        ram: "2500"
        cpu: "2" 
        ip: "192.168.0.100"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: master2
        box: "ubuntu/trusty64"
        ram: "2500"
        cpu: "1" 
        ip: "192.168.0.101"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: manager1
        box: "ubuntu/trusty64"
        ram: "4000"
        cpu: "2" 
        ip: "192.168.0.102"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: manager2
        box: "ubuntu/trusty64"
        ram: "6000"
        cpu: "2"
        ip: "192.168.0.103"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: edge
        box: "ubuntu/trusty64"
        ram: "3000"
        cpu: "1" 
        ip: "192.168.0.104"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: worker1
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.105"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: worker2
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.106"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: worker3
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.107"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: gw2
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1"
        ip: "192.168.0.109"
        provision: "worker.sh"
        folder: '/home/vagrant/fullstack'

      - name: gw1
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1"
        ip: "192.168.0.108"
        provision: "gw.sh"
        folder: '/home/vagrant/fullstack'
