---
# tasks file for preinstall
- name: "Disable IPV6"
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present
- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present

- name: "Configure Swappiness"
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
  tags: performance

- name: Disable transparent hugepage
  lineinfile:
    name: /etc/rc.local
    line: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  tags: performance

- name: "enable noatime"
  mount:
    name: "/"
    src: "/dev/sda1"
    fstype: "ext4"
    state: mounted
    opts: noatime
  tags: performance

- name: "Set Full Privilage to cma user"
  copy:
    src: sudoers
    dest: /etc/sudoers
  tags: cma

- name: "Create Cloudera Manager Service User"
  user:
    name: cma
    password: $6$eM1eZChnXKftJP$hVLcu3lx6FmGr4H3w1dVBh.dOhC6OJz0gFvM0vYkYJK9HjUGDfuTxmgXubN.SiYm2S.1VMjmYy9PSymM4BawU.
    group: sudo
    shell: "/bin/bash"
  tags: cma

#- name: "Get local repository"
#  apt_repository:
#    repo: deb http://192.168.1.10/ubuntu
#    state: present
#    update_cache: yes
#  tags:
#  - repo
#  - agent 
#  - jdk
- name: "install repo"
  shell: "sudo wget 'https://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/cloudera.list' \ -O /etc/apt/sources.list.d/cloudera.list"
- shell: "sudo apt update"


- name: "Auto accept JDK"
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: "Install JDK and CMA"
  apt:
    name:
      - oracle-j2sdk1.7
      - oracle-j2sdk1.6
      - oracle-java8-installer
      - cloudera-manager-agent
      - ntp
    state: installed
    update_cache: yes
    allow_unauthenticated: yes
  tags: installs
