---
      - name: master1
        box: "ubuntu/trusty64"
        ram: "1200"
        cpu: "2" 
        ip: "192.168.0.100"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: master2
        box: "ubuntu/trusty64"
        ram: "1200"
        cpu: "1" 
        ip: "192.168.0.101"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: manager1
        box: "ubuntu/trusty64"
        ram: "3096"
        cpu: "2" 
        ip: "192.168.0.102"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: manager2
        box: "ubuntu/trusty64"
        ram: "3048"
        cpu: "2"
        ip: "192.168.0.109"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: edge
        box: "ubuntu/trusty64"
        ram: "1500"
        cpu: "1" 
        ip: "192.168.0.104"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: worker1
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.105"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: worker2
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.106"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: worker3
        box: "ubuntu/trusty64"
        ram: "1000"
        cpu: "1" 
        ip: "192.168.0.107"
        provision: "worker.sh"
        folder: '/home/vagrant/hosts'

      - name: gw
        box: "ubuntu/trusty64"
        ram: "512"
        cpu: "1"
        ip: "192.168.0.108"
        provision: "gw.sh"
        folder: '/home/vagrant/hosts'
                                                                                                                                                                                                          
~                                        
