--- 
- hosts: cluster 
  tasks:
  - name: install apt-fast
    shell:  /bin/bash -c "$(curl -sL https://git.io/vokNn)"

  - name: get CMS list file
    get_url:
      url: https://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list
      dest: /etc/apt/sources.list.d/cloudera-manager.list

  - apt:
      update_cache: yes

  - name: install packages
    shell: apt-fast install -y oracle-j2sdk1.7 cloudera-manager-agent 
