---
    - name: install packages
      become: yes
      apt: 
        name: '{{ item }}' 
        allow_unauthenticated: yes
        update_cache: yes
      with_items:
        - "cloudera-manager-server"
        - "cloudera-manager-daemons"
      tags: install_cm

    - name: "Prepare DB for CM"
      become: yes
      shell: /usr/share/cmf/schema/scm_prepare_database.sh mysql scm scm scm_password
      tags: config_db
  
    - name: "Start CM service"
      become: yes
      service: 
        name: cloudera-scm-server 
        state: running
