---
 - hosts: manager
   become: yes
   tasks:
   - name: change line in file config
     lineinfile:
       name: /etc/cloudera-scm-agent/config.ini
       state: present
       regexp: "^server_host"
       line: "server_host=manager"

   - name: restart Cloudera-scm-agent
     service:
       name: cloudera-scm-agent
       state: restarted

   - pause:
       prompt: "Make Sure retrial liceanse is enable"

   - name: "setup cms"
     uri:
       url: http://manager:7180/api/v12/cm/service
       method: PUT
       user: admin
       password: admin
       body: "{{ lookup('file','{{ ansible_env.HOME}}/BenchmarksEdition/playbook/cmswithoutnav.json') }}"
       force_basic_auth: yes
       body_format: json
     tags: setup
   
   - name: "start cms"
     uri:
       url: http://manager:7180/api/v12/cm/service/commands/start
       method: POST
       user: admin
       password: admin
       body: "{{ lookup('file','{{ ansible_env.HOME}}/BenchmarksEdition/playbook/startwithoutnav.json') }}"
       force_basic_auth: yes
       body_format: json
       tags: startcms

 - hosts: cluster
   become: yes
   tasks:
   - name: change line in file config
     lineinfile:
       name: /etc/cloudera-scm-agent/config.ini
       state: present
       regexp: "^server_host"
       line: "server_host=manager"
   - name: restart Cloudera-scm-agent
     service:
       name: cloudera-scm-agent
       state: restarted
   - pause:
       minutes: 5
  
 - hosts: manager
   become: yes
   tasks:
   - name: "Import Template Json"
     uri:
       url: http://manager:7180/api/v12/cm/importClusterTemplate?addRepositories=true
       method: POST
       user: admin
       password: admin
       body: "{{ lookup('file','{{ ansible_env.HOME}}/BenchmarksEdition/playbook/template.json') }}"
       force_basic_auth: yes
       body_format: json
     tags: template
