---
# tasks file for postgress
- name: " Set Local Variable"
  shell: "{{ item }}"
  become: yes
  with_items:
   - 'update-locale LANGUAGE=en_US.UTF-8'
   - 'update-locale LANG=en_US.UTF-8'
   - 'update-locale LC_ALL=en_US.UTF-8'
   -  "locale-gen en_US.UTF-8"
   -  "dpkg-reconfigure locales"
  tags: variable

- name: "Install PostgreSQL"
  become: yes
  apt: 
    pkg: 
      - postgresql-9.3
      - python-pip
      - postgresql-server-dev-9.3
      - python-dev
    state: installed 
    update_cache: true
  tags: postgres

- name: "Install psycopg2"
  become: yes
  pip: 
    name: psycopg2 
  tags: postgres


- name: "Intialize DB CLuster"
  shell: pg_createcluster '{{ postgresql_version }}' main
  args: 
    creates: /etc/postgresql/9.3/main/start.conf
  tags: cluster

- name: "ensure postgres pg_hba is configured"
  become: yes
  copy: 
    src: "pg_hba.conf" 
    dest: "/etc/postgresql/9.3/main/pg_hba.conf"
    owner: postgres
    group: postgres
  tags: file
  notify:
   - restart postgres

- name: "Config Postgesql.conf"
  become: yes
  copy: 
    src: "postgresql.conf"
    dest: "/etc/postgresql/9.3/main/postgresql.conf"
    owner: postgres
    group: postgres
  tags: file
  notify:
    - restart postgres

- name: "Create Database Users"
  postgresql_user: 
    name: '{{ item }}' 
    password: '{{ item }}_password'
    encrypted: true
  with_items:
    - "{{ db_services }}"
  become: yes
  become_user: postgres
  tags: create_user

- name: "Create DB "
  postgresql_db: 
    name: '{{ item }}' 
    owner: '{{ item }}'
    encoding: UTF8
  with_items:
    - "{{ db_services }}"
  become: yes
  become_user: postgres
  tags: create_db

- name: "Additional shell configuration For Hive MetaStore"
  become: yes
  become_user: postgres
  shell: psql -c 'ALTER DATABASE hive SET standard_conforming_strings = off; '
  tags: add_hive
  when: "'hive' in db_services"

- name: "restart Postgres"
  become: yes
  become_user: postgres
  service:
    name: postgresql
    state: restarted
  tags: reload


