---
# tasks file for postgress
- name: " Set Local Variable"
  shell: "{{ item }}"
  become: yes
  with_items:
   - 'update-locale LANGUAGE=en_US.UTF-8'
   - 'update-locale LANG=en_US.UTF-8'
   - 'update-locale LC_ALL=en_US.UTF-8'
   -  "locale-gen en_US.UTF-8"
   -  "dpkg-reconfigure locales"

- name: "Install PostgreSQL"
  become: yes
  apt: 
    pkg: 
      - postgresql-9.3
      - python-pip
      - postgresql-server-dev-9.3
      - python-dev
    state: installed 
    update_cache: true


- name: "Install psycopg2"
  become: yes
  pip: 
    name: psycopg2 


- name: "Intialize DB CLuster"
  shell: pg_createcluster '{{ postgresql_version }}' main
  args: 
    creates: /etc/postgresql/9.3/main/start.conf

- name: "ensure postgres pg_hba is configured"
  become: yes
  copy: 
    src: "pg_hba.conf" 
    dest: "/etc/postgresql/9.3/main/pg_hba.conf"
    owner: root
    group: root
  notify:
   - restart postgres

- name: "Config Postgesql.conf"
  become: yes
  copy: 
    src: "postgresql.conf"
    dest: "/etc/postgresql/9.3/main/postgresql.conf"
    owner: root
    group: root
  notify:
    - restart postgres

- name: "Create Database Users"
  postgresql_user: 
    name: '{{ item }}' 
    password: '{{ item }}_password'
    encrypted: true
  with_items:
    - "{{ db_services }}"
  become: yes
  become_user: postgres

- name: "Create DB "
  postgresql_db: 
    name: '{{ item }}' 
    owner: '{{ item }}'
    encoding: UTF8
  with_items:
    - "{{ db_services }}"
  become: yes
  become_user: postgres


- name: "Additional shell configuration For Hive MetaStore"
  shell: psql -c 'ALTER DATABASE hive SET standard_conforming_strings = off;'
  become: yes
  become_user: postgres

- name: "Reloaded Postgres"
  become: yes
  become_user: postgres
  service: 
    name: postgresql
    state: reloaded

