---
# defaults file for postgress
# defaults file for roles/postgresql
postgresql_version: '9.3'
db_b.domain:
   - amon
   - rman
   - hive
   - sentry
   - nav
   - navms
   - oozie
   - scm


