---
- hosts: workers
  tasks:
    - name: Disable Access Logging Time
      mount:
        name: /
        src: LABEL=cloudimg-rootfs
        fstype: ext4 
        opts: defaults,noatime
        state: mounted
        
  
