---
- hosts: all

- tasks:
   - sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present
   - sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
   - sysctl: name=vm.swappiness value=10 state=present
