---
# tasks file for roles/galera
- name: Install MariaDB
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  apt: 
    pkg: 
      - mariadb-server
      - python-mysqldb
      - libmysql-java
    state: installed 
    force: yes
    update_cache: yes
    allow_unauthenticated: yes
  register: installed
  tags: installation

- name: Copy Configuration
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
  when: installed|success
  tags: config

- name: Change Bind in my.cnf
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: "bind-address"
    line: "bind-address=            x.x.x.x"


- name: restart MariaDB
  service:
    name: mysql
    state: restarted
    enabled: yes
  tags:
  - setup
  - stop

- name: "Debug DB access"
  shell:
    mysql -h localhost -u root -pAa123456
  register: can_connect
  ignore_errors: true
  tags: debug

- name: Secure Installation
  when: can_connect|failed
  include: ./secure_installation.yml
  tags: debug

- name: Create DB Tables
  mysql_db:
    name: '{{ item }}'
    login_password: Aa123456
    encoding: UTF8
  with_items:
    - "{{ db_b.domain }}"
  tags: 
  - tables
  - users

- name: Create Database Users
  mysql_user:
    host: "%"
    name: '{{ item }}'
    password: '{{ item }}_password'
    login_password: 'Aa123456'
    priv: "{{item}}.*:ALL"
  with_items:
    - "{{ db_b.domain }}"
  tags: users
