---
# tasks file for preinstall
- name: "Install python 2.7" 
  sudo: yes
  apt:
    name: python2.7
    state: present

- name: "Disable IPV6"
  become: yes
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
  become: yes

- name: "Congiure use of swapinness"
  become: yes
  sysctl:
    name: vm.swappiness
    value: 10
    state: present
#- name: " Add Repo JDK"
 # become: yes
#  apt_repository:
  #  repo: ppa:webupd8team/java
 #   update_cache: yes

#- name: "FIx Bug"
 # shell : sudo dpkg --configure -a

#- name: "Auto aceept JDK"
 #shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
 # sudo: yes

#- name: "Install JDK"
 # become: yes
 # shell: apt-get install -y oracle-java8-installer ca-certificates

#- name: "Java_HOME Variables"
#  shell: export JAVA_HOME=/usr/lib/jvm/java-8-oracle

#- name: "JRE_HOME Vraiable"
#  shell: export JRE_HOME=/usr/lib/jvm/java-8-oracle/jre

- name: "Set Full Privilage to cma user"
  become: yes
  copy:
    src: sudoers
    dest: /etc/sudoers

- name: "Create Cloudera Manager Service User"
  become: yes
  user:
    name: cma
    password: $6$eM1eZChnXKftJP$hVLcu3lx6FmGr4H3w1dVBh.dOhC6OJz0gFvM0vYkYJK9HjUGDfuTxmgXubN.SiYm2S.1VMjmYy9PSymM4BawU.
    group: sudo
    shell: "/bin/bash"

- name: "Get CMS list file"
  become: yes
  get_url: 
    url: "https://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list"
    dest: "/etc/apt/sources.list.d/cloudera-manager.list"
  tags: agent

- name: "Install JDK"
  become: yes
  apt:
    name:  oracle-j2sdk1.7
    state: installed
    update_cache: yes
    allow_unauthenticated: yes

- name: " install Cloudera Manager Agent"
  become: yes
  apt:
    name: cloudera-manager-agent
    state: installed
    allow_unauthenticated: yes
  tags: agent


 
  
