---
# tasks file for roles/haproxy
- name: install haproxy and keepalived
  apt:
    name:
      - haproxy
      - keepalived
    allow_unauthenticated: yes

- name: Allow Floating IP
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1

- name: Copy HAProxy Configurations
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Copy Master keepalived conf
  copy:
    src: keepalived_master.conf
    dest: /etc/keepalived/keepalived.conf
  when: master

- name: Copy Slave keepalived conf
  copy:
    src: keepalived_slave.conf
    dest: /etc/keepalived/keepalived.conf
  when: not master

- name: Start Services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - keepalived
    - haproxy
